### ISSUE TITLE
Docs: Interface/union type not displayed properly

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-playground#322] opened 2017-12-07 17:13 UTC
Interfaces and unions are currently displayed as a normal `type` definition. That's a bug.

## Example

This is the actual schema definition of the following schema:

```graphql
# Represents an owner of a Repository.
interface RepositoryOwner {
  # A URL pointing to the owner's public avatar.
  avatarUrl(
    # The size of the resulting square image.
    size: Int
  ): URI!
  id: ID!

  # The username used to login.
  login: String!

  # A list of repositories this user has pinned to their profile
  pinnedRepositories(
    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # If non-null, filters repositories according to privacy
    privacy: RepositoryPrivacy

    # Ordering options for repositories returned from the connection
    orderBy: RepositoryOrder

    # Affiliation options for repositories returned from the connection
    affiliations: [RepositoryAffiliation]

    # If non-null, filters repositories according to whether they have been locked
    isLocked: Boolean
  ): RepositoryConnection!

  # A list of repositories that the user owns.
  repositories(
    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # If non-null, filters repositories according to privacy
    privacy: RepositoryPrivacy

    # Ordering options for repositories returned from the connection
    orderBy: RepositoryOrder

    # Affiliation options for repositories returned from the connection
    affiliations: [RepositoryAffiliation]

    # If non-null, filters repositories according to whether they have been locked
    isLocked: Boolean

    # If non-null, filters repositories according to whether they are forks of another repository
    isFork: Boolean
  ): RepositoryConnection!

  # Find Repository.
  repository(
    # Name of Repository to find.
    name: String!
  ): Repository

  # The HTTP URL for the owner.
  resourcePath: URI!

  # The HTTP URL for the owner.
  url: URI!
}

```

![image](https://user-images.githubusercontent.com/1567498/33727572-ba1a1e48-db78-11e7-98a1-a5c4c49ca8f8.png)

**Comment by axos88** [comment] 2018-01-09 14:10
Just came to report this

**Comment by axos88** [comment] 2018-01-09 14:11
Seems to be a dupe of #171

**Closed** 2018-03-27 14:55 UTC
Labels: area/docs, bug, help wanted
