### ISSUE TITLE
Graphql Playground error - Empty Screen without any error message

### ISSUE THREAD

**Issue by freddy311082** [graphcool/graphql-playground#549] opened 2018-01-30 02:38 UTC
Hi Guys

I can't have access to any graphql server... After update to version 1.4.2, everytime I try to get access to any graphql server I get an empty screen just like you'll see bellow without any error message:

<img width="1206" alt="screen shot 2018-01-29 at 23 33 58" src="https://user-images.githubusercontent.com/4631733/35545295-2d0f051e-054d-11e8-9aad-98c7a2deed02.png">

I was looking for the place where Graphql Playground save its config but I couldn't find it... does anyone know what's going on here?

Regards

**Comment by naartjie** [comment] 2018-01-31 11:01
@freddy311082 I am getting a blank screen like that after running a couple of queries. 

Does anyone know how to run it in debug mode?

Version `1.4.2` on OS X.

**Comment by naartjie** [comment] 2018-01-31 11:21
I ran it via:
```sh
yarn
cd ./packages/graphql-playground-electron
yarn install
```

And I got this in the console, when the error happened, which was when I was browsing the schema, but it seems to be intermittent:

```
[1] [87613:0131/131729.349346:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
[1] 0   Electron Framework                  0x000000010693243c crashpad::CloseMultipleNowOrOnExec(int, int) + 970204
[1] 1   Electron Framework                  0x00000001068f9c53 crashpad::CloseMultipleNowOrOnExec(int, int) + 738803
[1] 2   Electron Framework                  0x00000001069116b1 crashpad::CloseMultipleNowOrOnExec(int, int) + 835665
[1] 3   Electron Framework                  0x00000001095ada9c crashpad::CloseMultipleNowOrOnExec(int, int) + 47612988
[1] 4   libnode.dylib                       0x000000010afea42e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20670
[1] 5   libnode.dylib                       0x000000010afea36e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20478
[1] 6   libnode.dylib                       0x000000010b47567a v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 27370
[1] 7   libnode.dylib                       0x000000010b46e570 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 76800
[1] 8   libnode.dylib                       0x000000010b46e8e4 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 77684
[1] 9   libnode.dylib                       0x000000010b47e11c v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 62860
[1] 10  Electron Framework                  0x0000000106971ae2 crashpad::CloseMultipleNowOrOnExec(int, int) + 1229954
[1] 11  Electron Framework                  0x0000000106919057 crashpad::CloseMultipleNowOrOnExec(int, int) + 866807
[1] 12  libsystem_pthread.dylib             0x00007fffc929993b _pthread_body + 180
[1] 13  libsystem_pthread.dylib             0x00007fffc9299887 _pthread_body + 0
[1] 14  libsystem_pthread.dylib             0x00007fffc929908d thread_start + 13
```

**Comment by tfiwm** [comment] 2018-02-13 07:44
Same for me! It happens often

**Comment by benjie** [comment] 2018-03-10 16:42
Just hit this myself; here's some screenshots to help you track it down:

![screenshot 2018-03-10 16 39 57](https://user-images.githubusercontent.com/129910/37244490-baa84f72-2481-11e8-85f2-6e2fd25d4e0f.png)

![screenshot 2018-03-10 16 39 30](https://user-images.githubusercontent.com/129910/37244493-c27590b6-2481-11e8-8be9-c1f2d0a1cd04.png)

It was caused by an error in my server logic; but the entire GraphQL Playground app went blank. 

This was the latest version on `brew` (installed a few hours ago) which then also prompted to update itself (and did so) - so should be up to date.

I believe the GraphQLPlayground is not defined error is harmless?

**Comment by seivan** [comment] 2018-03-20 13:01
I get this as well, but a total gray screen. I also get the error mentioned by @benjie 
`"GraphQLPlayground is not defined"`

`Version 1.4.5 (1.4.5.2716)`

**Comment by davidsyoung** [comment] 2018-03-21 11:26
Getting same issue here with a total gray screen, same error as @seivan above.

**Comment by sorenbs** [comment] 2018-04-08 13:59
We believe this is fixed in the latest release. Please reopen this issue if you experience it again, and remember to include your Playground version. Thanks!

**Closed by sorenbs** 2018-04-08 13:59 UTC

**Comment by thomasjfarley** [comment] 2018-04-20 01:16
this is still happening. i'm on version 1.5.3

**Comment by deftomat** [comment] 2018-04-25 04:33
Empty screen in 1.5.5. - "Cannot read property 'toJS' of undefined"

**Comment by nover** [comment] 2019-01-10 13:15
Also seeing this issue Version 1.8.5 (1.8.5) installed via `homebrew` in macOS mojave.

For me it happens during schema parse errors, where the dev console logs stuff like:
```
SyntaxError: Syntax Error: Expected :, found BlockString "....."
```
And then a snippet of our documentation for said field.

**Comment by MissLlq** [comment] 2019-04-16 07:34
Graphql Playground error - Empty Screen without any error message

TypeError: Cannot read property 'get' of undefined

**Comment by themmyloluwaa** [comment] 2019-08-25 08:30
hello, this issue is still happening and i'm on the 1.18.2 version. Here's a screenshot with some errors in the console.
![Screenshot (53)](https://user-images.githubusercontent.com/38155854/63647563-0432e700-c71b-11e9-9792-72468f3fda36.png)

**Comment by rgfx** [comment] 2019-11-14 04:45
in windows delete AppData\Roaming\GraphQL Playground. You will lose your data.

**Comment by themmyloluwaa** [comment] 2019-11-14 16:12
thank you.
